//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDriveAlbums.UI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneDriveAlbums.UI.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in as {0}.
        /// </summary>
        internal static string Connected_Msg {
            get {
                return ResourceManager.GetString("Connected_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string Connecting_Msg {
            get {
                return ResourceManager.GetString("Connecting_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix albums dates.
        /// </summary>
        internal static string FixDates_Btn {
            get {
                return ResourceManager.GetString("FixDates_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select interface language:.
        /// </summary>
        internal static string InterfaceLanguage_Lbl {
            get {
                return ResourceManager.GetString("InterfaceLanguage_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface language will be changed after application restart..
        /// </summary>
        internal static string InterfaceLanguageChanged_Warn {
            get {
                return ResourceManager.GetString("InterfaceLanguageChanged_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} items. {1:mm\:ss} elapsed.
        /// </summary>
        internal static string LoadedItems_Msg {
            get {
                return ResourceManager.GetString("LoadedItems_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading... {0} items found. {1:mm\:ss} elapsed.
        /// </summary>
        internal static string LoadingItems_Msg {
            get {
                return ResourceManager.GetString("LoadingItems_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive Albums.
        /// </summary>
        internal static string MainWindow_Caption {
            get {
                return ResourceManager.GetString("MainWindow_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0}.
        /// </summary>
        internal static string ProcessingItem_Msg {
            get {
                return ResourceManager.GetString("ProcessingItem_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready_Txt {
            get {
                return ResourceManager.GetString("Ready_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for:.
        /// </summary>
        internal static string SearchFor_Lbl {
            get {
                return ResourceManager.GetString("SearchFor_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 3 or more characters to search for.
        /// </summary>
        internal static string SearchFor_PlaceHolder {
            get {
                return ResourceManager.GetString("SearchFor_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SignIn_Btn {
            get {
                return ResourceManager.GetString("SignIn_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOut_Btn {
            get {
                return ResourceManager.GetString("SignOut_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        internal static string SortBy_Lbl {
            get {
                return ResourceManager.GetString("SortBy_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string SortByDate_Btn {
            get {
                return ResourceManager.GetString("SortByDate_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SortByName_Btn {
            get {
                return ResourceManager.GetString("SortByName_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        internal static string ViewAlbums_Btn {
            get {
                return ResourceManager.GetString("ViewAlbums_Btn", resourceCulture);
            }
        }
    }
}
